require: rubocop-rails

inherit_from:
  - .rubocop_disabled.yml
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'db/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'test/**/*'

# Metrics

Metrics/LineLength:
  Max: 120
  AllowURI: true
  Exclude:
    - config/routes.rb

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

# Style

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
  SupportedStyles:
    - require_parentheses
    - require_no_parentheses

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
